name: qbittorrent-ee
description: The qBittorrent project aims to provide an open-source software alternative
  to µTorrent.
annotations:
  title: qBittorrent
type: application
version: 1.1.1
apiVersion: v2
appVersion: latest
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.1.1
home: https://www.qbittorrent.org/,https://github.com/c0re100/qBittorrent-Enhanced-Edition
icon: https://media.sys.truenas.net/apps/qbittorrent/icons/icon.png
sources:
  - https://github.com/onedr0p/containers/tree/main/apps/qbittorrent
  - https://github.com/truenas/charts/tree/master/community/qbittorrent
  - https://www.qbittorrent.org/
  - https://github.com/c0re100/qBittorrent-Enhanced-Edition
keywords:
  - media
  - torrent
  - download
