image:
  repository: karurosuma/qbittorrent-ee
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

qbitConfig:
  additionalEnvs: []
qbitNetwork:
  webPort: 30024
  btPort: 50413
  hostNetwork: true
qbitRunAs:
  user: 568
  group: 568
qbitStorage:
  downloads:
    type: ixVolume
    datasetName: downloads
  config:
    type: ixVolume
    datasetName: config
  additionalStorages: []

notes:
  custom: |
    Default credentials:
    -  username: admin
    -  password: adminadmin
