image:
  repository: nyanmisaka/jellyfin
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

jellyfinConfig:
  publishedServerUrl: ''
  additionalEnvs: []
jellyfinGPU: {}
jellyfinNetwork:
  webPort: 30013
  hostNetwork: true
jellyfinRunAs:
  user: 100
  group: 100
jellyfinStorage:
  config:
    type: ixVolume
    datasetName: config
  cache:
    type: ixVolume
    datasetName: cache
  transcodes:
    type: ixVolume
    datasetName: transcodes
    medium: ''
    size: ''
  additionalStorages: []
